In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import umap
from sklearn.decomposition import PCA

In [63]:
X1= 10*np.random.rand(10, 5)
X2= 10*np.random.rand(15, 5)
X=np.concatenate([X1,X2], axis=0)

In [64]:
reducer = umap.UMAP(n_components=2, random_state=42)
reducer.fit(X)
X_umap = reducer.transform(X)
X1_umap = reducer.transform(X1)
X2_umap = reducer.transform(X2)




/neurospin/dico/fred/Runs/01_betaVAE/Program/venv/lib/python3.12/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


In [60]:
X1_umap

array([[ -7.039634 ,   2.1591506],
       [-10.601777 ,   4.227118 ],
       [-10.060386 ,   3.0721085],
       [ -6.292993 ,   2.9666595],
       [ -5.879044 ,   5.257264 ],
       [ -8.298993 ,   6.900441 ],
       [ -8.587313 ,   2.3341608],
       [ -5.524385 ,   4.3388715],
       [ -5.7418756,   3.5097523],
       [ -6.8520656,   2.293758 ]], dtype=float32)

In [61]:
X3_umap

array([[-9.639133 ,  5.761368 ],
       [-6.16236  ,  2.9215043],
       [-5.996741 ,  2.9026785],
       [-6.127262 ,  2.9127953],
       [-6.696467 ,  6.905852 ],
       [-9.915667 ,  2.915911 ],
       [-8.898786 ,  2.534638 ],
       [-9.6533   ,  5.9091854],
       [-9.130753 ,  6.2647977],
       [-9.540282 ,  5.827943 ],
       [-5.659954 ,  3.6412358],
       [-5.89869  ,  3.107488 ],
       [-5.780357 ,  5.9703546],
       [-6.2464952,  2.7570775],
       [-9.901785 ,  5.539077 ]], dtype=float32)

In [62]:
X4_umap

array([[ -7.039634 ,   2.1591506],
       [-10.601777 ,   4.227118 ],
       [-10.060386 ,   3.0721085],
       [ -6.292993 ,   2.9666595],
       [ -5.879044 ,   5.257264 ],
       [ -8.298993 ,   6.900441 ],
       [ -8.587313 ,   2.3341608],
       [ -5.524385 ,   4.3388715],
       [ -5.7418756,   3.5097523],
       [ -6.8520656,   2.293758 ],
       [ -5.800262 ,   5.2283907],
       [ -6.137462 ,   2.9384384],
       [ -5.6528444,   3.2491672],
       [ -9.536668 ,   6.184476 ],
       [ -6.842156 ,   7.1113334],
       [-10.390198 ,   3.349877 ],
       [ -8.894902 ,   2.5076506],
       [ -6.2475095,   2.7867095],
       [ -9.204536 ,   6.2036276],
       [ -9.607251 ,   5.8329697],
       [ -9.241407 ,   6.0102935],
       [ -5.8175488,   3.158407 ],
       [ -5.862538 ,   6.1110983],
       [ -6.312529 ,   2.7699347],
       [ -9.078944 ,   2.7363312]], dtype=float32)

PCA

In [34]:
pca = PCA(n_components=2)

In [ ]:
X3= np.concatenate([X1,10*np.random.rand(1, 5)], axis=0)

In [35]:
X_pca = pca.fit_transform(X)
X1_pca=pca.transform(X1)
X2_pca= pca.transform(X2)

In [36]:
X_pca

array([[-1.30717011,  3.10038442],
       [ 3.79030667, -4.60649831],
       [ 4.44147613,  3.60657948],
       [-2.89943634,  1.23219565],
       [ 1.34825793,  1.20407322],
       [ 3.72010741,  2.43336164],
       [ 5.71065016,  0.69633028],
       [-0.38988046, -3.39412463],
       [-1.23579368, -4.30490664],
       [ 6.14707294, -2.18028547],
       [-6.52875625, -0.76408273],
       [ 0.35494041, -3.05710709],
       [-2.50296258,  1.15151635],
       [-5.23337643,  1.78151478],
       [-0.05702427,  3.82145643],
       [-2.32861018,  1.33338241],
       [ 0.38096087,  2.0267695 ],
       [-2.4803976 , -2.4032963 ],
       [ 1.24494406,  0.76743644],
       [ 3.06219396, -0.85938831],
       [-2.5717123 ,  4.45310875],
       [ 2.35592099,  0.98029454],
       [-0.56651175,  4.21707369],
       [-4.90281029, -4.54217462],
       [ 0.4476107 , -6.6936135 ]])

In [37]:
X1_pca

array([[-1.30717011,  3.10038442],
       [ 3.79030667, -4.60649831],
       [ 4.44147613,  3.60657948],
       [-2.89943634,  1.23219565],
       [ 1.34825793,  1.20407322],
       [ 3.72010741,  2.43336164],
       [ 5.71065016,  0.69633028],
       [-0.38988046, -3.39412463],
       [-1.23579368, -4.30490664],
       [ 6.14707294, -2.18028547]])